#!/usr/bin/env bash
set -euo pipefail

cargo fmt --all

git diff --name-only --diff-filter=M | grep '\.rs$' | xargs -r git add

cargo clippy --workspace --all-targets -- \
  -D warnings \
  -A clippy::manual_is_multiple_of \
  -A clippy::too_many_arguments
