name: interstellar

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: interstellar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clients:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: clients

  counterparty:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: counterparty

  transfer:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: transfer

  query:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: query
